spring:
  datasource:
    url: jdbc:mysql://localhost:3307/book_trading?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&useUnicode=
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
